theme = "jetbrains_dark"

[editor]
true-color = true
line-number = "relative"
mouse = true
bufferline = "multiple"
auto-format = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"S-down" = "goto_next_paragraph"
"S-up" = "goto_prev_paragraph"
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[editor.cursor-shape]
insert = "bar"
