#[language-server.clangd]
#command = "clangd"
#args = ["--compile-commands-dir=.build/"]

[[language]]
name = "cpp"
formatter = { command = "clang-format", args = ["--style=file:.clang-format"] }
auto-format = true
#language-servers = [ "clangd" ]
